version: 1
disable_existing_loggers: false
formatters:
  precise:
    format: "[%(asctime)s.%(msecs)03d %(levelname)8s function=%(funcName)-12.12s L%(lineno)04d file=%(filename)-12.12s] %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: precise
  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    filename: uvicorn_log.log
    maxBytes: 10485760
    backupCount: 5
loggers:
  '':
    level: INFO
    handlers: [console, file_handler]
    propagate: true
  uvicorn.error:
    level: INFO
    handlers: [console, file_handler]
    propagate: true
    qualname: uvicorn.error
  uvicorn.access:
    level: INFO
    handlers: [console, file_handler]
    propagate: true
    qualname: uvicorn.access